### ISSUE TITLE
RSS feed parsing errors

### ISSUE THREAD

**Issue by ghost** [caryoscelus/caryoscelus.github.io#3]
Hello, at first, thanks for your work on https://github.com/zeronet-conservancy/zeronet-conservancy

Also, I have found your blog interesting, but can't subscribe using RSS reader

![2022-02-21_16-25](https://user-images.githubusercontent.com/96319366/154973889-0c82e607-740b-4095-8f98-4f24427ec434.png)

**Comment by caryoscelus** [comment]
hello and welcome ;) glad to hear rss is still a thing ^_^

thanks for reporting , i fixed the issue , it should be updated soon~~

**Comment by caryoscelus** [comment]
i haven't really tried rss in a long time so if it has more issues (with images or posts being cut wrongly) , feel free to report , should be easy enough to fix

**Comment by ghost** [comment]
it works, now, thank you!

also the same issue for the atom feed, 
even yes, I am RSS user <3

**Comment by caryoscelus** [comment]
fixed atom too , thx ^_^
